class CannotUndoTaskError(Exception):
    pass

class TaskNotFoundError(Exception):
    pass